name: Auto approve and merge

on: pull_request_target

jobs:
  auto-approve-and-merge:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write
    if: github.actor == 'exercism-solutions-syncer[bot]'
    steps:
      - uses: hmarr/auto-approve-action@v4
        with:
          review-message: "Auto approved automated PR"
      
      - name: Auto merge
        uses: pascalgn/automerge-action@v0.16.4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          merge_method: squash
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
